domain_path: C:\Users\user\Desktop\Projects\ECE4300_SP2026\GroupJ_Project\Code\Vitis\platform\export\platform\sw\standalone_microblaze_0
app_src_dir: C:\AMDDesignTools\2025.2\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
